server:
  port: 8080

spring:
  application:
    name: hostify
    version: 1.0.0
  profiles:
    active: ${DATABASE_PROFILE:mysql}
  config:
    import: application-security.yml
  banner:
    location: classpath:banner/hostify.txt
    charset: UTF-8
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true
